[package]
name = "AtCoder-Rust"
version = "0.1.0"
authors = ["Daisuke Hashimoto"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
